spring:
  ai:
    dashscope:
      api-key: ${ALI_DASHSCOPE_API_KEY:${DASHSCOPE_API_KEY:}}
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      mode: never
server:
  port: ${SERVER_PORT:8080}
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
knife4j:
  enable: false
search-api:
  api-key: ${SEARCH_API_KEY}
logging:
  level:
    root: INFO
    org.springframework.ai: INFO
